#!/bin/bash

#- make ARGS="--rm=false" build-prod-image
      - docker build -t ${KUBERNETES_SERVICE_NAME} -f Dockerfile --rm=false .
      - echo "aws configure set default.region eu-central-1"
      - aws configure set default.region eu-central-1
      # set default output to JSON
      - echo "aws configure set default.output json"
- aws configure set default.output json
